[package]
name = "note_utils"
version = "0.1.0"
edition = "2018"

[lib]
name = "note_utils"
path = "src/lib.rs"
doctest = false

[dependencies]
regex = "1.5.4"
binascii = "0.1"
rust-crypto = "^0.2"
chrono = { version = "0.4.19", features = ["serde"] }
lettre = "0.10.0-rc.3"
log = "0.4.14"
itertools = "0.10.1"
rand = "0.8.4"
percent-encoding = "2.1.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
thiserror = "1.0.26"
comrak = { version = "0.10.1", default-features = false }
lazy_static = "1.4.0"
openssl = "0.10.35"
url = { version = "2.2.2", features = ["serde"] }
actix-web = { version = "4.0.0-beta.8", default-features = false, features = ["rustls"] }
actix-rt = { version = "2.2.0", default-features = false }
anyhow = "1.0.41"
reqwest = { version = "0.11.4", features = ["json"] }
tokio = { version = "1.8.0", features = ["sync"] }
strum = "0.21.0"
strum_macros = "0.21.1"
futures = "0.3.15"
diesel = "1.4.7"
http = "0.2.4"
jsonwebtoken = "7.2.0"
deser-hjson = "1.0.1"
merge = "0.1.0"
envy = "0.4.2"
